### ISSUE TITLE
process_fragment_file.py   KeyError: 'KI270728.1'

### ISSUE THREAD

**Issue by shijianasdf** [spcdot/CopyscAT#17]
When I run process_fragment_file.py as follow
> ```r
>python process_fragment_file.py -i /Volumes/HDD4/HCC_mulimodel/FKRO22H000391_1A/atac_fragments.tsv.gz -o /Users/biofly/outputfile.tsv -b 1000000 -f 10000 -g /Users/biofly/hg38_chrom_sizes.tsv
> ```
I got error like this: 
> ```r
>Traceback (most recent call last):
>  File "process_fragment_file.py", line 105, in <module>
>    cell_ids[line_split[3]][line_split[0]][setIndex] += readLength
> KeyError: 'KI270728.1'
> ```

**Comment by spcdot** [comment]
Most likely your ATAC fragment file contains chromosomes that aren't in your chrom_sizes file. For downstream analysis I suggest removing all the alternative contigs etc, but for this step as long as you make sure your chrom_sizes and fragment file match up in terms of what's in there, it should run ok.

**Comment by shijianasdf** [comment]
> Most likely your ATAC fragment file contains chromosomes that aren't in your chrom_sizes file. For downstream analysis I suggest removing all the alternative contigs etc, but for this step as long as you make sure your chrom_sizes and fragment file match up in terms of what's in there, it should run ok.

I filtered the atac_fragment.tsv.gz based on chromosomes that aren't in my chrom_sizes file, and i run process_fragment_file.py as follow
> ```r
>python process_fragment_file.py -i /Volumes/HDD4/HCC_mulimodel/FKRO22H000391_1A/atac_fragments.tsv.gz -o /Users/biofly/outputfile.tsv -b 1000000 -f 10000 -g /Users/biofly/hg38_chrom_sizes.tsv
> ```
I got error like this: 
> ```r
>Initializing chromosomes
>Reading file
>Traceback (most recent call last):
>  File "process_fragment_file.py", line 101, in <module>
>    readLength = int(line_split[2]) - int(line_split[1]) - 1
>IndexError: list index out of range
> ```

**Comment by cathy-y** [comment]
I encountered the same issues. It would be helpful if process_fragment_file.py could perform the filtering step and yield a file that doesn't lead to an IndexError.

**Comment by Brawni** [comment]
same issue here. What's the easiest way to filter the fragment file or add the missing contig names to the chrom_sizes file?

**Comment by spcdot** [comment]
Thanks for the feedback - I'll try to make the process_fragments script a little smarter so it doesn't crash with contigs not identified in the chrom_sizes file but rather gives a warning. Will post an update once this is done.

**Comment by spcdot** [comment]
Ok - just updated the code for the process_fragments script - it will now print a warning and ignore lines that are not in the chrom_sizes file. This should fix the issue.
